services:
  gateway:
    container_name: gateway
    image: nginx:latest
    networks:
      - account
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - account

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    networks:
      - account
  
  account-db:
    container_name: account-db
    image: mongo:latest
    networks:
      - account
    volumes:
      - ./account/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cesi
      MONGO_INITDB_ROOT_PASSWORD: cesi
      
networks:
  account: