services:
  gateway:
    container_name: gateway
    image: nginx:latest
    networks:
      - account
      - payment
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - account
      - payment

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    networks:
      - account
  
  account-db:
    container_name: account-db
    image: mongo:latest
    networks:
      - account
    volumes:
      - ./account/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cesi
      MONGO_INITDB_ROOT_PASSWORD: cesi

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    networks:
      - payment
  
  payment-db:
    container_name: payment-db
    image: mongo:latest
    networks:
      - payment
    volumes:
      - ./payment/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cesi
      MONGO_INITDB_ROOT_PASSWORD: cesi
      
networks:
  account:
  payment: