services:
  gateway:
    container_name: gateway
    image: nginx:latest
    networks:
      - authentication
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authentication

  authentication:
    container_name: authentication
    build:
      context: ./authentication
      dockerfile: Dockerfile
    networks:
      - authentication
  
  authentication-db:
    container_name: authentication-db
    image: mongo:latest
    networks:
      - authentication
    volumes:
      - ./authentication/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cesi
      MONGO_INITDB_ROOT_PASSWORD: cesi
      
networks:
  authentication: