name: Continous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-deploy:
    name: Run test
    runs-on: unbuntu-latest
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      - name: setup NodeJS env
        uses: actions/setup-node@v4       
        with:
          node-version: 21
      
      - name: Install des dépendances
        run: npm ci

      - run: npm build

      #run les test unitaire de notre code
      - run: npm test

      #crée version exec du projet (Nom-projet-1.0.0.tgz)
      - run: npm pack 